import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Modal from "@/components/Modal";
import TransactionContext from "@/components/TransactionContext";
import MeContext from "@/components/MeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased lg:h-screen`}
      >
        <MeContext>
          <TransactionContext>
            <Modal>
              {children}
            </Modal>
          </TransactionContext>
        </MeContext>
      </body>
    </html>
  );
}
